Repository Come-On-App/Come-On-Frontend, pull requests merged in 2022-12, with the labels that each got.

#1 Config: ESLint, Prettier 설정 브랜치 병합
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
Labels: :memo: 리뷰

#2 🍕 [branchName] : Create pull_request_template.md
  pull_request_template.md
Labels: :memo: 리뷰

#4 🍕 [bananana0118-patch-1] : Config 파일 수정
  pull_request_template.md
Labels: :memo: 리뷰

#3 🍕 [jeongbaebang-patch-1] : Create issue_template.md
  issue_template.md
Labels: :memo: 리뷰

#10 ☀️ Config : test commit
  pull_request_template.md
Labels: :memo: 리뷰

#12 🍕 [config] : ESLint Ruls 추가 & package.json 내용 추가
  .eslintrc.json
  package.json
Labels: :memo: 리뷰, 🔨 기능구현

#13 🍕 [styles] : 전역 테마 색상 & 타입 설정
  .eslintrc.json
  constants/Colors.ts
  package-lock.json
  package.json
  types.tsx
Labels: :memo: 리뷰, 🎨 스타일링

#14 🍕 [ feature-fontFamily ] : 폰트파일 추가 및 설정
  .eslintrc.json
  App.tsx
  assets/fonts/BlackHanSans-Regular.ttf
  assets/fonts/Pretendard-Medium.ttf
  constants/Layout.ts
  hooks/useCachedResources.ts
  package-lock.json
  screens/ModalScreen.tsx
  screens/TabOneScreen.tsx
  screens/TabTwoScreen.tsx
Labels: :memo: 리뷰, 🔨 기능구현
