Repository Come-On-App/Come-On-Frontend, pull requests merged in 2023-04, with the labels that each got.

#118 [Feature] 로그인 로직 수정, 리팩토링
  src/components/button/KakaoLoginBtn.tsx
  src/components/calendar/Calendar.tsx
  src/components/calendar/CustomCalendarTheme.tsx
  src/components/calendar/DateModal.tsx
  src/components/input/InputForm.tsx
  src/components/input/InputImage.tsx
  src/components/meetingCard/CardTop.tsx
  src/components/member/MemberBox.tsx
  src/components/myPage/MyPageLogoutButton.tsx
  src/constants/themed.ts
  src/features/meetingSlice.tsx
  src/hooks/useAuth.ts
  src/hooks/useMeeting.ts
  src/hooks/useSubscribe.ts
  src/navigation/index.tsx
  src/screens/CreateMeeting.tsx
  src/screens/LoginScreen.tsx
  src/screens/PeriodCalender.tsx
  src/screens/SelectCalendar.tsx
  src/screens/bottomTap/TabOneScreen.tsx
  src/screens/meeting/detail/common.tsx
  src/screens/meeting/detail/date.tsx
  src/types/index.ts
  src/types/navigation.ts
  src/utils/image.ts
Labels: :zap: API, :gear: 리팩토링, 🔨 기능구현

#119 🍕 [Feature] : 기능 업데이트 (게시물 신고 & 리팩토링)
  .eslintrc.json
  .gitignore
  App.tsx
  app.config.ts
  babel.config.js
  eas.json
  package.json
  react-native-maps-plugin.js
  src/components/Image.tsx
  src/components/InviteCode.tsx
  src/components/Layout.tsx
  src/components/SearchBar.tsx
  src/components/input/InputImage.tsx
  src/components/input/InputText.tsx
  src/components/meeting/DateContainer.tsx
  src/components/meeting/TimePicker.tsx
  src/components/meeting/_timepicker.tsx
  src/components/meetingCard/CardDisplay.tsx
  src/components/meetingCard/CardList.tsx
  src/components/meetingCard/CardMenu.tsx
  src/components/meetingCard/CardModal.tsx
  src/components/meetingCard/CardText.tsx
  src/components/member/MemberBox.tsx
  src/components/myPage/MyPageNickName.tsx
  src/components/report/ReportButton.tsx
  src/components/report/ReportDiscription.tsx
  src/components/report/ReportImage.tsx
  src/components/report/ReportTitle.tsx
  src/components/report/common.tsx
  src/constants/config.ts
  src/hooks/useGoTo.ts
  src/hooks/useImagePicker.ts
  src/navigation/index.tsx
  src/screens/EventScreen.tsx
  src/screens/bottomTap/TabOneScreen.tsx
  src/screens/meeting/detail/Member.tsx
  src/screens/meeting/detail/common.tsx
  src/screens/meeting/detail/date.tsx
  src/screens/meeting/detail/place.tsx
  src/screens/place/Select.tsx
  src/screens/reportPost/ReportPost.tsx
  src/types/component.card.ts
  src/types/component.report.ts
  src/types/index.ts
  src/types/navigation.ts
  src/utils/__tests__/promise.spec.ts
  src/utils/fn.ts
  src/utils/image.ts
  src/utils/promise.ts
  tsconfig.json
  yarn.lock
Labels: :memo: 리뷰, :gear: 리팩토링, 🎨 스타일링, 🔨 기능구현

#121 🍕 [Feature] : 모달캘린더 추가
  src/api/meeting/members.ts
  src/components/button/FlexButtons.tsx
  src/components/calendar/Calendar.tsx
  src/components/calendar/ModalCalendar.tsx
  src/navigation/index.tsx
  src/screens/bottomTap/TabOneScreen.tsx
  src/screens/meeting/create/CreateMeeting.tsx
  src/screens/meeting/create/PeriodCalender.tsx
  src/screens/meeting/detail/SelectCalendar.tsx
  src/types/meeting.calendar.ts
Labels: 🎨 스타일링, 🔨 기능구현

#126 [Feature]
  src/components/input/InputForm.tsx
  src/screens/bottomTap/TabOneScreen.tsx
Labels: :lady_beetle: 버그

#128 🔨 Refactor : 캘린더 최적화
  src/components/calendar/Calendar.tsx
  src/components/calendar/DateModal.tsx
  src/components/calendar/ModalCalendar.tsx
  src/components/calendar/PeriodArrowCalendar.tsx
  src/screens/meeting/create/PeriodCalender.tsx
  src/types/meeting.calendar.ts
Labels: :gear: 리팩토링

#130 🦊 Fix : 오류 수정
  app.config.ts
  src/api/user/user.ts
  src/components/button/CancelIconButton.tsx
  src/hooks/query/useUserQuery.ts
  src/hooks/useSubscribe.ts
  src/screens/meeting/detail/index.tsx
  src/screens/place/Select.tsx
  src/types/api.user.ts
  src/utils/fn.ts
  src/utils/secureStore.ts
Labels: :lady_beetle: 버그

#131 🍕 [Feature] : 세팅페이지 추가
  src/api/user/user.ts
  src/assets/images/logo/GoogleLogo.tsx
  src/components/button/GoogleLoginBtn.tsx
  src/components/button/KakaoLoginBtn.tsx
  src/components/myPage/SettingButton.tsx
  src/constants/config.ts
  src/navigation/index.tsx
  src/screens/LoginScreen.tsx
  src/screens/login/Apple.tsx
  src/screens/meeting/detail/SelectCalendar.tsx
  src/screens/settingScreen/IconTitle.tsx
  src/screens/settingScreen/SettingScreen.tsx
  src/types/api.user.ts
  src/types/component.button.ts
  src/types/navigation.ts
Labels: :zap: API, :memo: 리뷰, :gear: 리팩토링, 🎨 스타일링, 🔨 기능구현

#132 ➕ Add : 회원탈퇴 모달창 추가
  src/components/button/CancelButton.tsx
  src/components/button/ConfirmButton.tsx
  src/components/button/FlexButtons.tsx
  src/components/button/GoogleLoginBtn.tsx
  src/components/button/KakaoLoginBtn.tsx
  src/constants/config.ts
  src/screens/LoginScreen.tsx
  src/screens/login/Apple.tsx
  src/screens/settingScreen/IconTitle.tsx
  src/screens/settingScreen/SettingScreen.tsx
Labels: :memo: 리뷰, :gear: 리팩토링, 🔨 기능구현

#133 🖌️ Modify : 로그인 시 재요청 안되는 이슈 해결
  src/api/auth/auth.ts
  src/screens/settingScreen/SettingScreen.tsx
Labels: :memo: 리뷰, :gear: 리팩토링, 🔨 기능구현

#134 🍕 [Feature] : 권한 메시지 수정
  app.config.ts
  eas.json
  package.json
  src/components/InviteCode.tsx
  yarn.lock
Labels: 🔨 기능구현

#135 🍕 [Feature] : v1 api v2로 업그레이드
  src/api/auth/auth.ts
  src/features/authSlice.ts
  src/hooks/query/useMeetingQuery.ts
  src/hooks/useAuth.ts
  src/screens/meeting/detail/SelectCalendar.tsx
  src/screens/settingScreen/SettingScreen.tsx
Labels: :gear: 리팩토링, 🔨 기능구현
